### ISSUE TITLE
Unable to update Magisk app.


### ISSUE THREAD

**Issue by DarkCoder0** [kantjer/MagiskFiles#3]
Hello..
After 28 May  , I am unable to update from the updater . It keeps saying package is currupted/conflicting. Don't know why. ! Never happened before . 🤔 Is this because you changed someone of apk k signature or something like that.. ? 🤔
Thanks ..

**Comment by CHEF-KOCH** [comment]
Unfortunately, Magisk manager doesn't check or verify the downloaded packages, which means if the package is downloaded incorrectly it gives you the error without any chance to re-download the package to 'correct' this. 

Just go to /Magiskmanager folder, delete the corrupt package or apk and try to re-download it, it will work then.

**Comment by DarkCoder0** [comment]
@CHEF-KOCH still not working .. 
Here see this video.. 
.
https://photos.app.goo.gl/QCIUObP0XHhNBkyu2

**Comment by CHEF-KOCH** [comment]
Ah now I know what you mean, indeed this has nothing to do with the package by itself and I haven't seen the problem myself because I use LuckyPatcher 'allow installation of apps with different signature' option.

Yeah, you need to uninstall your old version first, the signature is still the same but [since the symlink changed](https://forum.xda-developers.com/showpost.php?p=76042873&postcount=41) it might be detected as 'new'.
